name: Deploy Astro site to Pages

on:
  push:
    branches: ["main"]  # Trigger on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # Ensures GITHUB_TOKEN can push to repo

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build the site
      - name: Build site
        run: npm run build

      # 5️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   # default token, no PAT needed
          publish_dir: ./dist
          publish_branch: gh-pages                    # branch to deploy to
          force_orphan: true                          # create branch if it doesn't exist
